language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.4.*"
  - SYMFONY_VERSION="4.0.*"

matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION="4.0.*" # Symfony >= 4.0 PHP requirement is ^7.1.3
    - php: 7.0
      env: SYMFONY_VERSION="4.0.*" # Symfony >= 4.0 PHP requirement is ^7.1.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-add travis.php.ini
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: eugone.yann@gmail.com
